export enum CandidateStatus {
  NEW = 'NEW',
  FED = 'FED',
  SCREENING = 'SCREENING',
  INTERVIEWING = 'INTERVIEWING',
  OFFERED = 'OFFERED',
  HIRED = 'HIRED',
  REJECTED = 'REJECTED',
  WITHDREW = 'WITHDREW',
  PROBATION = 'PROBATION',
  DRAFT = 'DRAFT',
  ARCHIVED = 'ARCHIVED',
}
