import { BaseModel } from '../base.model';

// export enum MarketingSeoKeywordMessagePattern {
//   COMMON_MARKETING_SEO_KEYWORD_LIST = 'COMMON_MARKETING_SEO_KEYWORD_LIST',
//   COMMON_MARKETING_SEO_KEYWORD_GET = 'COMMON_MARKETING_SEO_KEYWORD_GET',
//   COMMON_MARKETING_SEO_KEYWORD_CREATE = 'COMMON_MARKETING_SEO_KEYWORD_CREATE',
//   COMMON_MARKETING_SEO_KEYWORD_UPDATE = 'COMMON_MARKETING_SEO_KEYWORD_UPDATE',
//   COMMON_MARKETING_SEO_KEYWORD_DELETE = 'COMMON_MARKETING_SEO_KEYWORD_DELETE',
// }

export interface MarketingSeoKeyword extends BaseModel {
  readonly keyword?: string;
  readonly templateName?: string;
}
