// export enum AuthOAuthType {
//   FACEBOOK = 'FACEBOOK',
//   GOOGLE = 'GOOGLE',
//   LINKEDIN = 'LINKEDIN',
// }

// export enum AuthMessagePattern {
//   AUTH_AUTH_LOGIN = 'AUTH_AUTH_LOGIN',
//   AUTH_AUTH_LOGIN_OAUTH = 'AUTH_AUTH_LOGIN_OAUTH',
//   AUTH_AUTH_SIGN_UP = 'AUTH_AUTH_SIGN_UP',
//   AUTH_AUTH_VERIFY_EMAIL = "AUTH_AUTH_VERIFY_EMAIL",
//   AUTH_AUTH_RESEND_VERIFICATION_CODE = "AUTH_AUTH_RESEND_VERIFICATION_CODE",
//   AUTH_AUTH_REQUEST_RESET_PASSWORD = 'AUTH_AUTH_REQUEST_RESET_PASSWORD',
//   AUTH_AUTH_CREATE_PASSWORD = 'AUTH_AUTH_CREATE_PASSWORD',
//   AUTH_AUTH_UPDATE_PASSWORD = 'AUTH_AUTH_UPDATE_PASSWORD',
//   AUTH_AUTH_GET_PROFILE = 'AUTH_AUTH_GET_PROFILE',
//   AUTH_AUTH_UPDATE_PROFILE = 'AUTH_AUTH_UPDATE_PROFILE',
// }

export {};
