import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { HealthModule, RedisCacheService } from '@jobhopin/core';

import {
  SourceModule,
  CountryModule,
  CityModule,
  CompanyTypeModule,
  DistrictModule,
  DegreeModule,
  UniversityModule,
  DepartmentModule,
  SettingModule,
  SkillModule,
  BannerModule,
  IndustryModule,
  PlatformModule,
  MarketingBannerModule,
  MarketingKeywordModule,
  MarketingSeoKeywordModule,
  BenefitModule,
  HeadcountModule,
  LocationModule,
  LocationTypeModule,
  LanguageModule,
  LevelModule,
  SalaryModule,
  SalaryReviewModule,
  TagFunctionModule,
  TagSubFunctionModule,
  YearOfExperienceModule,
  SortTypeModule,
  ThumdownReasonModule,
  SuggestedSkillModule,
  KeywordModule,
  HighlightCompanyModule,
  AssignedJobModule,
  FeedbackModule,
} from '@app/modules';
@Module({
  imports: [
    FeedbackModule,
    AssignedJobModule,
    BannerModule,
    SourceModule,
    CountryModule,
    BenefitModule,
    CityModule,
    LocationModule,
    LocationTypeModule,
    CompanyTypeModule,
    DistrictModule,
    DegreeModule,
    DepartmentModule,
    HeadcountModule,
    HealthModule,
    UniversityModule,
    SettingModule,
    SkillModule,
    IndustryModule,
    PlatformModule,
    MarketingBannerModule,
    MarketingKeywordModule,
    MarketingSeoKeywordModule,
    LanguageModule,
    LevelModule,
    SalaryModule,
    SalaryReviewModule,
    TagFunctionModule,
    TagSubFunctionModule,
    ThumdownReasonModule,
    YearOfExperienceModule,
    SortTypeModule,
    SuggestedSkillModule,
    KeywordModule,
    HighlightCompanyModule,
    MongooseModule.forRoot(process.env.COMMON_SERVICE_MONGODB_URL),
  ],
  controllers: [],
  providers: [RedisCacheService],
})
export class AppModule {}
