export const enum Environment {
  DEVELOPMENT = 'development',
  STAGING = 'staging',
  PRODUCTION = 'production',
}

export const enum RedisCacheKey {
  MARKET_INSIGHT_INDUSTRY_MISC = 'market-insight-industry-misc',
  LANGUAGE_MISC = 'language-misc',
  LEVEL_MISC = 'level-misc',
  MARKET_INSIGHT_LEVEL_MISC = 'market-insight-level-misc',
  LOCATION_SELECTION_MISC = 'location-selection-misc',
  SALARY_MISC = 'salary-misc',
  SALARY_REVIEW_FILTER_DATA_MISC = 'salary-review-filter-data-misc',
  SORT_TYPE_MISC = 'sort-type-misc',
  TAG_FUNCTION_MISC = 'tag-function-misc',
  UNIVERSITY_MISC = 'university-misc',
  YEAR_OF_EXPERIENCE_MISC = 'year-of-experience-misc',
  LOCATION_QUERY = 'location-query',
  CITY_QUERY = 'city-query',
  DEPARTMENT_QUERY = 'department-query',
  DEGREE_QUERY = 'degree-query',
  INDUSTRY_QUERY = 'industry-query',
  HEADCOUNT_QUERY = 'headcount-query',
  DISTRICT_QUERY = 'district-query',
  BENEFIT_QUERY = 'benefit-query',
  COMPANY_TYPE_QUERY = 'company-query',
  LANGUAGE_QUERY = 'language-query',
  LOCATION_TYPE_QUERY = 'location-type-query',
  BANNER_QUERY = 'banner-query',
}
