export enum ExceptionMessage {
  // Common
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  NOT_ACCEPTABLE = 'NOT_ACCEPTABLE',
  PROXY_AUTHENTICATION_REQUIRED = 'PROXY_AUTHENTICATION_REQUIRED',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  // Infas
  MICRO_METHOD_NOT_FOUND = 'MICRO_METHOD_NOT_FOUND',
  MICRO_SERVICE_NOT_FOUND = 'MICRO_SERVICE_NOT_FOUND',
  INVALID_CLIENT_CONFIG = 'INVALID_CLIENT_CONFIG',
  CLIENT_CONNECTION_FAILED = 'CLIENT_CONNECTION_FAILED',

  // Auth
  AUTHORIZATION_HEADER_NOT_FOUND = 'AUTHORIZATION_HEADER_NOT_FOUND',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_TOKEN_FORMAT = 'INVALID_TOKEN_FORMAT',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  INVALID_ACCOUNT = 'INVALID_ACCOUNT',

  // File
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  INVALID_FILE_SIZE = 'INVALID_FILE_SIZE',
  INVALID_FILE_COUNT = 'INVALID_FILE_COUNT',
  INVALID_INPUT = 'INVALID_INPUT',
}
