export enum ExceptionMessage {
  // Common
  BAD_REQUEST = 'common.BAD_REQUEST',
  UNAUTHORIZED = 'common.UNAUTHORIZED',
  FORBIDDEN = 'common.FORBIDDEN',
  NOT_FOUND = 'common.NOT_FOUND',
  NOT_ACCEPTABLE = 'common.NOT_ACCEPTABLE',
  PROXY_AUTHENTICATION_REQUIRED = 'common.PROXY_AUTHENTICATION_REQUIRED',
  REQUEST_TIMEOUT = 'common.REQUEST_TIMEOUT',
  TOO_MANY_REQUESTS = 'common.TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR = 'common.INTERNAL_SERVER_ERROR',
  NOT_IMPLEMENTED = 'common.NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE = 'common.SERVICE_UNAVAILABLE',
  METHOD_NOT_ALLOWED = 'common.METHOD_NOT_ALLOWED',

  // Core
  INVALID_CONFIG = 'common.INVALID_CONFIG',
  MICRO_METHOD_NOT_FOUND = 'common.MICRO_METHOD_NOT_FOUND',
  MICRO_SERVICE_NOT_FOUND = 'common.MICRO_SERVICE_NOT_FOUND',
  CLIENT_CONNECTION_FAILED = 'common.CLIENT_CONNECTION_FAILED',
  UNDERGOING_MAINTENANCE = 'common.UNDERGOING_MAINTENANCE',
  INVALID_INPUT = 'common.INVALID_INPUT',
  SOMETHING_WHEN_WRONG = 'common.SOMETHING_WHEN_WRONG',
  ERROR_TITLE = 'common.ERROR_TITLE',

  // File
  INVALID_FILE_TYPE = 'common.INVALID_FILE_TYPE',
  INVALID_FILE_SIZE = 'common.INVALID_FILE_SIZE',
  INVALID_FILE_COUNT = 'common.INVALID_FILE_COUNT',

  // Auth
  AUTHORIZATION_HEADER_NOT_FOUND = 'auth.AUTHORIZATION_HEADER_NOT_FOUND',
  INVALID_TOKEN = 'auth.INVALID_TOKEN',
  REFRESH_TOKEN_NOT_SETUP = 'auth.REFRESH_TOKEN_NOT_SETUP',
  INVALID_TOKEN_FORMAT = 'auth.INVALID_TOKEN_FORMAT',
  TOKEN_EXPIRED = 'auth.TOKEN_EXPIRED',
  INVALID_PAYLOAD = 'auth.INVALID_PAYLOAD',
  INVALID_ACCOUNT = 'auth.INVALID_ACCOUNT',
}
