import { Injectable } from '@nestjs/common';
import { TableMapping } from '../../interfaces/table-mapping.interface';

@Injectable()
export class TableMappingService {
  private TABLE_MAPPING_ACTIVITY: Array<TableMapping>;
  private TABLE_MAPPING_BLOG: Array<TableMapping>;
  private TABLE_MAPPING_CHAT: Array<TableMapping>;
  private TABLE_MAPPING_COMMON: Array<TableMapping>;
  private TABLE_MAPPING_CANDIDATE: Array<TableMapping>;
  private TABLE_MAPPING_CV: Array<TableMapping>;
  private TABLE_MAPPING_JOB: Array<TableMapping>;
  private TABLE_MAPPING_JOBSEEKER: Array<TableMapping>;
  private TABLE_MAPPING_QUIZZ: Array<TableMapping>;
  private TABLE_MAPPING_LUCKY_SPIN: Array<TableMapping>;
  private TABLE_MAPPING_ORGANIZATION: Array<TableMapping>;
  private TABLE_MAPPING_USERS: Array<TableMapping>;

  private TABLE_MAPPING_OTHER: Array<TableMapping>;

  private TABLE_MAPPINGS: Array<TableMapping> = [];

  constructor() {
    this.TABLE_MAPPING_ACTIVITY = [
      new TableMapping(
        'ai_api_tracking',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'ai_api_tracking',
        '',
      ),
      new TableMapping(
        'api_calling',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'api_calling',
        '',
      ),
      new TableMapping(
        'jobhop_emailhistory',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'jobhop_emailhistory',
        'updated',
      ),
      new TableMapping(
        'django_admin_log',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'django_admin_log',
        'actionTime',
      ),
      new TableMapping(
        'blog_notification_log',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'blog_notification_log',
        '',
      ),
      new TableMapping(
        'custom_notification_log',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'custom_notification_log',
        '',
      ),
      new TableMapping(
        'notification_log',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'notification_log',
        '',
      ),
      new TableMapping(
        'outboundtracking_mailtracking',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'outboundtracking_mailtracking',
        '',
      ),
      new TableMapping(
        'outboundtracking_mailtrackingaction',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'outboundtracking_mailtrackingaction',
        '',
      ),
      new TableMapping(
        'process_cv_log',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'process_cv_log',
        '',
      ),
      new TableMapping(
        'search_history',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'search_history',
        'updatedAt',
      ),
      new TableMapping(
        'tranhis',
        'id',
        process.env.MONGODB_DATABASE_ACTIVITY,
        'tranhis',
        '',
      ),
    ];

    this.TABLE_MAPPING_BLOG = [
      new TableMapping(
        'blog_content',
        'content_id',
        process.env.MONGODB_DATABASE_BLOG,
        'blog_content',
        'updateDate',
      ),
      new TableMapping(
        'blog_post',
        'id',
        process.env.MONGODB_DATABASE_BLOG,
        'blog_post',
        '',
      ),
      new TableMapping(
        'blog_post_digest',
        'post_id',
        process.env.MONGODB_DATABASE_BLOG,
        'blog_post_digest',
        '',
      ),
      new TableMapping(
        'blog_post_favorite',
        'id',
        process.env.MONGODB_DATABASE_BLOG,
        'blog_post_favorite',
        '',
      ),
    ];

    this.TABLE_MAPPING_CHAT = [
      new TableMapping(
        'chat_conversation',
        'id',
        process.env.MONGODB_DATABASE_CHAT,
        'chat_conversation',
        'lastUpdatedTime',
      ),
      new TableMapping(
        'chat_conversation_member',
        'id',
        process.env.MONGODB_DATABASE_CHAT,
        'chat_conversation_member',
        'dateUpdated',
      ),
      new TableMapping(
        'chat_media_file',
        'id',
        process.env.MONGODB_DATABASE_CHAT,
        'chat_media_file',
        '',
      ),
      new TableMapping(
        'chat_media_message',
        'id',
        process.env.MONGODB_DATABASE_CHAT,
        'chat_media_message',
        'dateUpdated',
      ),
      new TableMapping(
        'chat_message',
        'id',
        process.env.MONGODB_DATABASE_CHAT,
        'chat_message',
        'dateUpdated',
      ),
      new TableMapping(
        'chat_suggested_message',
        'id',
        process.env.MONGODB_DATABASE_CHAT,
        'chat_suggested_message',
        'updatedAt',
      ),
      new TableMapping(
        'chat_user',
        'id',
        process.env.MONGODB_DATABASE_CHAT,
        'chat_user',
        'dateUpdated',
      ),
      new TableMapping(
        'chat_user_conversation',
        'id',
        process.env.MONGODB_DATABASE_CHAT,
        'chat_user_conversation',
        'updatedAt',
      ),
    ];

    this.TABLE_MAPPING_COMMON = [
      new TableMapping(
        'city',
        'city_id',
        process.env.MONGODB_DATABASE_COMMON,
        'city',
        'lastUpdate',
      ),
      new TableMapping(
        'country',
        'country_id',
        process.env.MONGODB_DATABASE_COMMON,
        'country',
        'lastUpdate',
      ),
      new TableMapping(
        'banner',
        'id',
        process.env.MONGODB_DATABASE_COMMON,
        'banner',
        'updatedAt',
      ),
      new TableMapping(
        'degree',
        'id',
        process.env.MONGODB_DATABASE_COMMON,
        'degree',
        'lastUpdate',
      ),
      new TableMapping(
        'department',
        'department_id',
        process.env.MONGODB_DATABASE_COMMON,
        'department',
        'lastUpdate',
      ),
      new TableMapping(
        'district',
        'district_id',
        process.env.MONGODB_DATABASE_COMMON,
        'district',
        'lastUpdate',
      ),
      new TableMapping(
        'industry',
        'industry_id',
        process.env.MONGODB_DATABASE_COMMON,
        'industry',
        'lastUpdate',
      ),
      new TableMapping(
        'marketing_banner',
        'id',
        process.env.MONGODB_DATABASE_COMMON,
        'marketing_banner',
        'updatedAt',
      ),
      new TableMapping(
        'marketing_keyword',
        'id',
        process.env.MONGODB_DATABASE_COMMON,
        'marketing_keyword',
        'updatedAt',
      ),
      new TableMapping(
        'marketing_seo_keyword',
        'id',
        process.env.MONGODB_DATABASE_COMMON,
        'marketing_seo_keyword',
        '',
      ),
      new TableMapping(
        'platform',
        'id',
        process.env.MONGODB_DATABASE_COMMON,
        'platform',
        'updated',
      ),
      new TableMapping(
        'setting',
        'id',
        process.env.MONGODB_DATABASE_COMMON,
        'setting',
        '',
      ),
      new TableMapping(
        'skill',
        'id',
        process.env.MONGODB_DATABASE_COMMON,
        'skill',
        'lastUpdate',
      ),
      new TableMapping(
        'source',
        'id',
        process.env.MONGODB_DATABASE_COMMON,
        'source',
        'lastUpdate',
      ),
      new TableMapping(
        'university',
        'id',
        process.env.MONGODB_DATABASE_COMMON,
        'university',
        'updatedAt',
      ),
    ];

    this.TABLE_MAPPING_CANDIDATE = [
      new TableMapping(
        'candidate',
        'candidate_id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate',
        'lastUpdate',
      ),
      new TableMapping(
        'candidate_attach',
        'id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_attach',
        'lastUpdate',
      ),
      new TableMapping(
        'candidate_company_type',
        'id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_company_type',
        '',
      ),
      new TableMapping(
        'candidate_feedback_group',
        'id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_feedback_group',
        'updatedAt',
      ),
      new TableMapping(
        'candidate_feedback_group_content',
        'id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_feedback_group_content',
        'updatedAt',
      ),
      new TableMapping(
        'candidate_feedback_item',
        'id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_feedback_item',
        'updatedAt',
      ),
      new TableMapping(
        'candidate_feedback_item_content',
        'id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_feedback_item_content',
        'updatedAt',
      ),
      new TableMapping(
        'candidate_function',
        'id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_function',
        '',
      ),
      new TableMapping(
        'candidate_industry',
        'id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_industry',
        '',
      ),
      new TableMapping(
        'candidate_link',
        'link_id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_link',
        'lastUpdate',
      ),
      new TableMapping(
        'candidate_location',
        'id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_location',
        '',
      ),
      new TableMapping(
        'candidate_perference_history',
        'id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_perference_history',
        'updatedAt',
      ),
      new TableMapping(
        'candidate_thumbdown_count',
        'id',
        process.env.MONGODB_DATABASE_CANDIDATE,
        'candidate_thumbdown_count',
        'updatedAt',
      ),
    ];

    this.TABLE_MAPPING_CV = [
      new TableMapping(
        'cv',
        'cv_id',
        process.env.MONGODB_DATABASE_CV,
        'cv',
        'lastUpdate',
      ),
      new TableMapping(
        'cv_analysis_flow',
        'id',
        process.env.MONGODB_DATABASE_CV,
        'cv_analysis_flow',
        'updatedAt',
      ),
      new TableMapping(
        'cv_attach',
        'id',
        process.env.MONGODB_DATABASE_CV,
        'cv_attach',
        'lastUpdate',
      ),
      new TableMapping(
        'cv_feedback',
        'cv_feedback_id',
        process.env.MONGODB_DATABASE_CV,
        'cv_feedback',
        'lastUpdate',
      ),
      new TableMapping(
        'cv_history',
        'id',
        process.env.MONGODB_DATABASE_CV,
        'cv_history',
        '',
      ),
      new TableMapping(
        'cv_industry',
        'id',
        process.env.MONGODB_DATABASE_CV,
        'cv_industry',
        'lastUpdate',
      ),
      new TableMapping(
        'cv_link',
        'cv_id',
        process.env.MONGODB_DATABASE_CV,
        'cv_link',
        'lastUpdate',
      ),
      new TableMapping(
        'cv_mailbox',
        'id',
        process.env.MONGODB_DATABASE_CV,
        'cv_mailbox',
        '',
      ),
      new TableMapping(
        'cv_score',
        'cv_id',
        process.env.MONGODB_DATABASE_CV,
        'cv_score',
        '',
      ),
      new TableMapping(
        'cv_skill',
        'cv_skill_id',
        process.env.MONGODB_DATABASE_CV,
        'cv_skill',
        'lastUpdate',
      ),
      new TableMapping(
        'cv_tag',
        'id',
        process.env.MONGODB_DATABASE_CV,
        'cv_tag',
        'updatedAt',
      ),
      new TableMapping(
        'cv_templates',
        'id',
        process.env.MONGODB_DATABASE_CV,
        'cv_templates',
        '',
      ),
    ];

    this.TABLE_MAPPING_JOB = [
      new TableMapping(
        'job',
        'job_id',
        process.env.MONGODB_DATABASE_JOB,
        'job',
        'lastUpdate',
      ),
      new TableMapping(
        'job_ai_lysis',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_ai_lysis',
        'updatedAt',
      ),
      new TableMapping(
        'job_board_apply_log',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_board_apply_log',
        '',
      ),
      new TableMapping(
        'job_bounty',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_bounty',
        'updatedAt',
      ),
      new TableMapping(
        'job_bounty_history',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_bounty_history',
        'updatedAt',
      ),
      new TableMapping(
        'job_budget',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_budget',
        'updated',
      ),
      new TableMapping(
        'job_budget_history',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_budget_history',
        'updated',
      ),
      new TableMapping(
        'job_budget_log',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_budget_log',
        'updated',
      ),
      new TableMapping(
        'job_budget_request',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_budget_request',
        'updated',
      ),
      new TableMapping(
        'job_budget_request_added',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_budget_request_added',
        'updated',
      ),
      new TableMapping(
        'job_budget_suggest_info',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_budget_suggest_info',
        'updated',
      ),
      new TableMapping(
        'job_category',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_category',
        'updatedAt',
      ),
      new TableMapping(
        'job_favorite',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_favorite',
        'lastUpdate',
      ),
      new TableMapping(
        'job_interview',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_interview',
        'updated',
      ),
      new TableMapping(
        'job_interview_CS_in_charge',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_interview_CS_in_charge',
        '',
      ),
      new TableMapping(
        'job_interview_SC_in_charge',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_interview_SC_in_charge',
        '',
      ),
      new TableMapping(
        'job_interview_TI_in_charge',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_interview_TI_in_charge',
        '',
      ),
      new TableMapping(
        'job_interview_category',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_interview_category',
        'updated',
      ),
      new TableMapping(
        'job_like',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_like',
        'lastUpdate',
      ),
      new TableMapping(
        'job_link',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_link',
        'lastUpdate',
      ),
      new TableMapping(
        'job_salary_template',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_salary_template',
        'lastUpdate',
      ),
      new TableMapping(
        'job_score',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_score',
        '',
      ),
      new TableMapping(
        'job_search',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_search',
        '',
      ),
      new TableMapping(
        'job_search_quota',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_search_quota',
        'updatedAt',
      ),
      new TableMapping(
        'job_stats',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_stats',
        'updated',
      ),
      new TableMapping(
        'job_stats_detail',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_stats_detail',
        'updated',
      ),
      new TableMapping(
        'job_subscription_history',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_subscription_history',
        'updatedAt',
      ),
      new TableMapping(
        'job_template',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_template',
        'lastUpdate',
      ),
      new TableMapping(
        'job_templates',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_templates',
        'updatedAt',
      ),
      new TableMapping(
        'job_thumdown_reason',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_thumdown_reason',
        '',
      ),
      new TableMapping(
        'job_title',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_title',
        '',
      ),
      new TableMapping(
        'job_title_salary_range',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_title_salary_range',
        '',
      ),
      new TableMapping(
        'job_type',
        'job_type_id',
        process.env.MONGODB_DATABASE_JOB,
        'job_type',
        'lastUpdate',
      ),
      new TableMapping(
        'job_version',
        'job_version_id',
        process.env.MONGODB_DATABASE_JOB,
        'job_version',
        '',
      ),
      new TableMapping(
        'job_view',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'job_view',
        '',
      ),
      new TableMapping(
        'job_view_raw',
        'view_id',
        process.env.MONGODB_DATABASE_JOB,
        'job_view_raw',
        '',
      ),
      new TableMapping(
        'jobgroup',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobgroup',
        'updatedAt',
      ),
      new TableMapping(
        'jobgroup_burnt_credits',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobgroup_burnt_credits',
        'updatedAt',
      ),
      new TableMapping(
        'jobgroup_jobs',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobgroup_jobs',
        '',
      ),
      new TableMapping(
        'jobhop_blacklistdomain',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_blacklistdomain',
        '',
      ),
      new TableMapping(
        'jobhop_fptoladipagelog',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_fptoladipagelog',
        'updatedAt',
      ),
      new TableMapping(
        'jobhop_genericdomain',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_genericdomain',
        '',
      ),
      new TableMapping(
        'jobhop_historicalorganization',
        'history_id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_historicalorganization',
        'lastUpdate',
      ),
      new TableMapping(
        'jobhop_internaluseremail',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_internaluseremail',
        'updated',
      ),
      new TableMapping(
        'jobhop_jobatsactivity',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_jobatsactivity',
        'updatedAt',
      ),
      new TableMapping(
        'jobhop_jobcategory',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_jobcategory',
        '',
      ),
      new TableMapping(
        'jobhop_jobdefaultimage',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_jobdefaultimage',
        '',
      ),
      new TableMapping(
        'jobhop_joblocation',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_joblocation',
        '',
      ),
      new TableMapping(
        'jobhop_jobmatchcounter',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_jobmatchcounter',
        'update',
      ),
      new TableMapping(
        'jobhop_jobsetting',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_jobsetting',
        '',
      ),
      new TableMapping(
        'jobhop_notimessagedetail',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_notimessagedetail',
        'updated',
      ),
      new TableMapping(
        'jobhop_organizationbenefit',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_organizationbenefit',
        'updated',
      ),
      new TableMapping(
        'jobhop_paymentlink',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_paymentlink',
        'update',
      ),
      new TableMapping(
        'jobhop_scorenotification',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_scorenotification',
        '',
      ),
      new TableMapping(
        'jobhop_scorenotification_missing_fields',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_scorenotification_missing_fields',
        '',
      ),
      new TableMapping(
        'jobhop_scorenotificationgroup',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_scorenotificationgroup',
        '',
      ),
      new TableMapping(
        'jobhop_scorenotificationmissingfield',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_scorenotificationmissingfield',
        '',
      ),
      new TableMapping(
        'jobhop_suggestedkeyword',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_suggestedkeyword',
        'update',
      ),
      new TableMapping(
        'jobhop_useractivity',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_useractivity',
        'updated',
      ),
      new TableMapping(
        'jobhop_userattemptlogin',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_userattemptlogin',
        'updated',
      ),
      new TableMapping(
        'jobhop_userjobsentrecc',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_userjobsentrecc',
        '',
      ),
      new TableMapping(
        'jobhop_usermanual',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_usermanual',
        '',
      ),
      new TableMapping(
        'jobhop_userscorenotification',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_userscorenotification',
        '',
      ),
      new TableMapping(
        'jobhop_userscoresentnotification',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobhop_userscoresentnotification',
        '',
      ),
      new TableMapping(
        'jobinterview_history',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobinterview_history',
        'updated',
      ),
      new TableMapping(
        'jobmatch',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobmatch',
        'lastUpdate',
      ),
      new TableMapping(
        'jobmatch_budget_sent',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobmatch_budget_sent',
        'updated',
      ),
      new TableMapping(
        'jobmatch_page_testimonial',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobmatch_page_testimonial',
        'updated',
      ),
      new TableMapping(
        'jobmatch_page_testimonialcontent',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobmatch_page_testimonialcontent',
        'updated',
      ),
      new TableMapping(
        'jobmatch_page_videolink',
        'id',
        process.env.MONGODB_DATABASE_JOB,
        'jobmatch_page_videolink',
        'updated',
      ),
    ];

    this.TABLE_MAPPING_JOBSEEKER = [
      new TableMapping(
        'jobseeker',
        'jobseeker_id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker',
        'lastUpdate',
      ),
      new TableMapping(
        'jobseeker_activity_date',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_activity_date',
        '',
      ),
      new TableMapping(
        'jobseeker_address_g_place',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_address_g_place',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_award',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_award',
        'lastUpdate',
      ),
      new TableMapping(
        'jobseeker_career_interest_card',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_career_interest_card',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_city',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_city',
        '',
      ),
      new TableMapping(
        'jobseeker_crawler',
        'crawler_id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_crawler',
        'lastUpdate',
      ),
      new TableMapping(
        'jobseeker_cv',
        'jobseeker_cv_id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_cv',
        'lastUpdate',
      ),
      new TableMapping(
        'jobseeker_cv_email_segment',
        'cv_id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_cv_email_segment',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_cv_overwrite',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_cv_overwrite',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_directly_apply',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_directly_apply',
        '',
      ),
      new TableMapping(
        'jobseeker_district',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_district',
        '',
      ),
      new TableMapping(
        'jobseeker_education',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_education',
        'lastUpdate',
      ),
      new TableMapping(
        'jobseeker_email_segment',
        'segment_id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_email_segment',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_entity_view',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_entity_view',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_followed_organizations',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_followed_organizations',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_industry',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_industry',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_interest',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_interest',
        'lastUpdate',
      ),
      new TableMapping(
        'jobseeker_job_alert',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_job_alert',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_job_expected',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_job_expected',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_job_function',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_job_function',
        '',
      ),
      new TableMapping(
        'jobseeker_job_referral',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_job_referral',
        '',
      ),
      new TableMapping(
        'jobseeker_job_saved',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_job_saved',
        'lastUpdate',
      ),
      new TableMapping(
        'jobseeker_job_type',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_job_type',
        '',
      ),
      new TableMapping(
        'jobseeker_language',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_language',
        'lastUpdate',
      ),
      new TableMapping(
        'jobseeker_level_expected',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_level_expected',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_location',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_location',
        '',
      ),
      new TableMapping(
        'jobseeker_market_value',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_market_value',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_matchscore',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_matchscore',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_recommendation_jobs',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_recommendation_jobs',
        '',
      ),
      new TableMapping(
        'jobseeker_reference',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_reference',
        'lastUpdate',
      ),
      new TableMapping(
        'jobseeker_segment_routine',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_segment_routine',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_skill',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_skill',
        'lastUpdate',
      ),
      new TableMapping(
        'jobseeker_titlecase',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_titlecase',
        '',
      ),
      new TableMapping(
        'jobseeker_verify_account',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_verify_account',
        'updatedAt',
      ),
      new TableMapping(
        'jobseeker_verify_account_file',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_verify_account_file',
        '',
      ),
      new TableMapping(
        'jobseeker_view_profile',
        'view_id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_view_profile',
        '',
      ),
      new TableMapping(
        'jobseeker_work_experience',
        'id',
        process.env.MONGODB_DATABASE_JOBSEEKER,
        'jobseeker_work_experience',
        'lastUpdate',
      ),
    ];

    this.TABLE_MAPPING_QUIZZ = [
      new TableMapping(
        'quiz',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_action_log',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_action_log',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_category',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_category',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_entry_point',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_entry_point',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_event',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_event',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_language',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_language',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_log_question_answered',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_log_question_answered',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_match_log',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_match_log',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_question',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_question',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_question_answer',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_question_answer',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_question_media',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_question_media',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_score_log',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_score_log',
        'updatedAt',
      ),
      new TableMapping(
        'quiz_vote_log',
        'id',
        process.env.MONGODB_DATABASE_QUIZZ,
        'quiz_vote_log',
        'updatedAt',
      ),
    ];
    this.TABLE_MAPPING_LUCKY_SPIN = [
      new TableMapping(
        'game_assessment_test_job_history',
        'id',
        process.env.MONGODB_DATABASE_LUCKY_SPIN,
        'game_assessment_test_job_history',
        'updatedAt',
      ),
      new TableMapping(
        'game_leader_board_bot',
        'id',
        process.env.MONGODB_DATABASE_LUCKY_SPIN,
        'game_leader_board_bot',
        'updatedAt',
      ),
      new TableMapping(
        'game_lucky_spin',
        'id',
        process.env.MONGODB_DATABASE_LUCKY_SPIN,
        'game_lucky_spin',
        'updatedAt',
      ),
      new TableMapping(
        'game_lucky_spin_history',
        'id',
        process.env.MONGODB_DATABASE_LUCKY_SPIN,
        'game_lucky_spin_history',
        'updatedAt',
      ),
      new TableMapping(
        'game_lucky_spin_item',
        'id',
        process.env.MONGODB_DATABASE_LUCKY_SPIN,
        'game_lucky_spin_item',
        'updatedAt',
      ),
      new TableMapping(
        'game_lucky_spin_match',
        'id',
        process.env.MONGODB_DATABASE_LUCKY_SPIN,
        'game_lucky_spin_match',
        'updatedAt',
      ),
      new TableMapping(
        'game_score_turn_log',
        'id',
        process.env.MONGODB_DATABASE_LUCKY_SPIN,
        'game_score_turn_log',
        'updatedAt',
      ),
      new TableMapping(
        'game_turn_log',
        'id',
        process.env.MONGODB_DATABASE_LUCKY_SPIN,
        'game_turn_log',
        'updatedAt',
      ),
      new TableMapping(
        'game_user_session',
        'id',
        process.env.MONGODB_DATABASE_LUCKY_SPIN,
        'game_user_session',
        'updatedAt',
      ),
    ];

    this.TABLE_MAPPING_ORGANIZATION = [
      new TableMapping(
        'organization',
        'organization_id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization',
        'lastUpdate',
      ),
      new TableMapping(
        'organization_article',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_article',
        'updatedAt',
      ),
      new TableMapping(
        'organization_custom_url',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_custom_url',
        'updatedAt',
      ),
      new TableMapping(
        'organization_expired_package',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_expired_package',
        'updated',
      ),
      new TableMapping(
        'organization_first_job',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_first_job',
        'updatedAt',
      ),
      new TableMapping(
        'organization_insider',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_insider',
        'updated',
      ),
      new TableMapping(
        'organization_insider_view',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_insider_view',
        '',
      ),
      new TableMapping(
        'organization_leader_profile',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_leader_profile',
        '',
      ),
      new TableMapping(
        'organization_license_verify',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_license_verify',
        '',
      ),
      new TableMapping(
        'organization_media',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_media',
        'lastUpdate',
      ),
      new TableMapping(
        'organization_package',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_package',
        'lastUpdate',
      ),
      new TableMapping(
        'organization_package_history',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_package_history',
        'updatedAt',
      ),
      new TableMapping(
        'organization_package_log',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_package_log',
        'updated',
      ),
      new TableMapping(
        'organization_platform',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_platform',
        'updated',
      ),
      new TableMapping(
        'organization_recruiter',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_recruiter',
        'updatedAt',
      ),
      new TableMapping(
        'organization_review',
        'review_id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_review',
        '',
      ),
      new TableMapping(
        'organization_review_detail',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_review_detail',
        'updated_date',
      ),
      new TableMapping(
        'organization_review_reaction',
        'reaction_review_id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_review_reaction',
        'updated_date',
      ),
      new TableMapping(
        'organization_section',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_section',
        'updatedAt',
      ),
      new TableMapping(
        'organization_similar_company',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_similar_company',
        '',
      ),
      new TableMapping(
        'organization_size',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_size',
        '',
      ),
      new TableMapping(
        'organization_tranasction',
        'id',
        process.env.MONGODB_DATABASE_ORGANIZATION,
        'organization_tranasction',
        'updatedAt',
      ),
    ];

    this.TABLE_MAPPING_USERS = [
      new TableMapping(
        'user_action',
        'id',
        process.env.MONGODB_DATABASE_USERS,
        'user_action',
        '',
      ),
      new TableMapping(
        'user_cv_template',
        'id',
        process.env.MONGODB_DATABASE_USERS,
        'user_cv_template',
        'updatedAt',
      ),
      new TableMapping(
        'user_email_verification',
        'id',
        process.env.MONGODB_DATABASE_USERS,
        'user_email_verification',
        'updatedAt',
      ),
      new TableMapping(
        'user_location',
        'id',
        process.env.MONGODB_DATABASE_USERS,
        'user_location',
        'updatedAt',
      ),
      new TableMapping(
        'user_setting',
        'id',
        process.env.MONGODB_DATABASE_USERS,
        'user_setting',
        '',
      ),
      new TableMapping(
        'users_activation',
        'id',
        process.env.MONGODB_DATABASE_USERS,
        'users_activation',
        'updated',
      ),
      new TableMapping(
        'users_cv',
        'id',
        process.env.MONGODB_DATABASE_USERS,
        'users_cv',
        'updatedAt',
      ),
      new TableMapping(
        'users_platform',
        'id',
        process.env.MONGODB_DATABASE_USERS,
        'users_platform',
        'updated',
      ),
      new TableMapping(
        'user_tatent_keyword',
        'id',
        process.env.MONGODB_DATABASE_USERS,
        'user_tatent_keyword',
        'updated',
      ),
      new TableMapping(
        'users',
        'user_id',
        process.env.MONGODB_DATABASE_USERS,
        'users',
        'lastUpdate',
      ),
    ];

    this.TABLE_MAPPING_OTHER = [
      new TableMapping(
        'account_deletion',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'account_deletion',
        '',
      ),
      new TableMapping(
        'account_group',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'account_group',
        '',
      ),
      new TableMapping(
        'account_group_permissions',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'account_group_permissions',
        '',
      ),
      new TableMapping(
        'account_invitation',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'account_invitation',
        '',
      ),
      new TableMapping(
        'account_permission',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'account_permission',
        '',
      ),
      new TableMapping(
        'account_user_group',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'account_user_group',
        '',
      ),
      new TableMapping(
        'account_user_permission',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'account_user_permission',
        '',
      ),
      new TableMapping(
        'accounts_user',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'accounts_user',
        '',
      ),
      new TableMapping(
        'accounts_user_groups',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'accounts_user_groups',
        '',
      ),
      new TableMapping(
        'accounts_user_user_permissions',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'accounts_user_user_permissions',
        '',
      ),
      new TableMapping(
        'activecampaign_setting',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'activecampaign_setting',
        '',
      ),
      new TableMapping(
        'activity',
        'activity_id',
        process.env.MONGODB_DATABASE_OTHER,
        'activity',
        'lastUpdate',
      ),
      new TableMapping(
        'address_g_place',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'address_g_place',
        'updatedAt',
      ),
      new TableMapping(
        'app_update_notification',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'app_update_notification',
        '',
      ),
      new TableMapping(
        'app_version',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'app_version',
        'updatedAt',
      ),
      new TableMapping(
        'assigned_job',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'assigned_job',
        'updated',
      ),
      new TableMapping(
        'assisted_token',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'assisted_token',
        'updatedAt',
      ),
      new TableMapping(
        'auth_group',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'auth_group',
        '',
      ),
      new TableMapping(
        'auth_group_permissions',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'auth_group_permissions',
        '',
      ),
      new TableMapping(
        'auth_permission',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'auth_permission',
        '',
      ),
      new TableMapping(
        'benefit',
        'benefit_id',
        process.env.MONGODB_DATABASE_OTHER,
        'benefit',
        'lastUpdate',
      ),
      new TableMapping(
        'blacklist_domain',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'blacklist_domain',
        'updatedAt',
      ),
      new TableMapping(
        'bug_report',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'bug_report',
        '',
      ),
      new TableMapping(
        'bug_report_file',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'bug_report_file',
        '',
      ),
      new TableMapping(
        'claim_account',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'claim_account',
        'updatedAt',
      ),
      new TableMapping(
        'claim_user_trigger',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'claim_user_trigger',
        'updatedAt',
      ),
      new TableMapping(
        'company',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'company',
        'updatedAt',
      ),
      new TableMapping(
        'company_review_content',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'company_review_content',
        'updated_date',
      ),
      new TableMapping(
        'company_type',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'company_type',
        'updatedAt',
      ),
      new TableMapping(
        'coupon',
        'coupon_id',
        process.env.MONGODB_DATABASE_OTHER,
        'coupon',
        'updatedAt',
      ),
      new TableMapping(
        'custom_notification',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'custom_notification',
        '',
      ),
      new TableMapping(
        'custom_notification_job',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'custom_notification_job',
        '',
      ),
      new TableMapping(
        'device_token',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'device_token',
        '',
      ),
      new TableMapping(
        'email_subscription',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'email_subscription',
        'lastUpdate',
      ),
      new TableMapping(
        'email_subscription_control',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'email_subscription_control',
        'updatedAt',
      ),
      new TableMapping(
        'employee_profile',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'employee_profile',
        'updated',
      ),
      new TableMapping(
        'employee_profile_company_types',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'employee_profile_company_types',
        '',
      ),
      new TableMapping(
        'employee_profile_favorite',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'employee_profile_favorite',
        'updated',
      ),
      new TableMapping(
        'employee_profile_feedback',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'employee_profile_feedback',
        'updated',
      ),
      new TableMapping(
        'employee_profile_functions',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'employee_profile_functions',
        '',
      ),
      new TableMapping(
        'employee_profile_industries',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'employee_profile_industries',
        '',
      ),
      new TableMapping(
        'employee_profile_locations',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'employee_profile_locations',
        '',
      ),
      new TableMapping(
        'employee_profile_matched_cv',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'employee_profile_matched_cv',
        'updated',
      ),
      new TableMapping(
        'employee_profile_referals',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'employee_profile_referals',
        '',
      ),
      new TableMapping(
        'employee_profile_skills',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'employee_profile_skills',
        '',
      ),
      new TableMapping(
        'employee_profile_tags',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'employee_profile_tags',
        '',
      ),
      new TableMapping(
        'faq',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'faq',
        'updatedAt',
      ),
      new TableMapping(
        'faq_category',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'faq_category',
        'updatedAt',
      ),
      new TableMapping(
        'faq_feedback',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'faq_feedback',
        '',
      ),
      new TableMapping(
        'feedback',
        'feedback_id',
        process.env.MONGODB_DATABASE_OTHER,
        'feedback',
        'lastUpdate',
      ),
      new TableMapping(
        'feedback_hopscore',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'feedback_hopscore',
        '',
      ),
      new TableMapping(
        'feedback_market_value',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'feedback_market_value',
        '',
      ),
      new TableMapping(
        'feedback_text',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'feedback_text',
        '',
      ),
      new TableMapping(
        'fpto_top_company',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'fpto_top_company',
        '',
      ),
      new TableMapping(
        'groups',
        'group_id',
        process.env.MONGODB_DATABASE_OTHER,
        'groups',
        'lastUpdate',
      ),
      new TableMapping(
        'headcount',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'headcount',
        '',
      ),
      new TableMapping(
        'highlight_company',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'highlight_company',
        'updatedAt',
      ),
      new TableMapping(
        'highlighted_industry',
        'industry_id',
        process.env.MONGODB_DATABASE_OTHER,
        'highlighted_industry',
        'lastUpdate',
      ),
      new TableMapping(
        'home_page_statistics',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'home_page_statistics',
        '',
      ),
      new TableMapping(
        'home_setting',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'home_setting',
        'updatedAt',
      ),
      new TableMapping(
        'hsct_api_log',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'hsct_api_log',
        '',
      ),
      new TableMapping(
        'hsct_user',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'hsct_user',
        'updatedAt',
      ),
      new TableMapping(
        'import_file',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'import_file',
        'updatedAt',
      ),
      new TableMapping(
        'integration_hs_ac_contact',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'integration_hs_ac_contact',
        'updatedAt',
      ),
      new TableMapping(
        'integration_r_profile',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'integration_r_profile',
        'lastUpdate',
      ),
      new TableMapping(
        'integration_user_profile',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'integration_user_profile',
        'lastUpdate',
      ),
      new TableMapping(
        'interview',
        'interview_id',
        process.env.MONGODB_DATABASE_OTHER,
        'interview',
        'lastUpdate',
      ),
      new TableMapping(
        'interview_feedback',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'interview_feedback',
        '',
      ),
      new TableMapping(
        'interview_review',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'interview_review',
        'updatedAt',
      ),
      new TableMapping(
        'interview_review_comment',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'interview_review_comment',
        'updatedAt',
      ),
      new TableMapping(
        'interview_review_comment_mention',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'interview_review_comment_mention',
        'updatedAt',
      ),
      new TableMapping(
        'interview_review_question',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'interview_review_question',
        'updatedAt',
      ),
      new TableMapping(
        'interview_review_question_answer',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'interview_review_question_answer',
        'updatedAt',
      ),
      new TableMapping(
        'interview_review_reaction',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'interview_review_reaction',
        'updatedAt',
      ),
      new TableMapping(
        'interviewer',
        'interviewer_id',
        process.env.MONGODB_DATABASE_OTHER,
        'interviewer',
        'lastUpdate',
      ),
      new TableMapping(
        'keyword',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'keyword',
        '',
      ),
      new TableMapping(
        'language',
        'language_id',
        process.env.MONGODB_DATABASE_OTHER,
        'language',
        'lastUpdate',
      ),
      new TableMapping(
        'level',
        'level_id',
        process.env.MONGODB_DATABASE_OTHER,
        'level',
        'lastUpdate',
      ),
      new TableMapping(
        'location',
        'location_id',
        process.env.MONGODB_DATABASE_OTHER,
        'location',
        '',
      ),
      new TableMapping(
        'location_type',
        'location_type_id',
        process.env.MONGODB_DATABASE_OTHER,
        'location_type',
        '',
      ),
      new TableMapping(
        'logs',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'logs',
        '',
      ),
      new TableMapping(
        'map_group_role',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'map_group_role',
        'lastUpdate',
      ),
      new TableMapping(
        'map_interview',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'map_interview',
        'lastUpdate',
      ),
      new TableMapping(
        'map_job_function',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'map_job_function',
        '',
      ),
      new TableMapping(
        'map_user_group',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'map_user_group',
        'lastUpdate',
      ),
      new TableMapping(
        'map_user_role',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'map_user_role',
        'lastUpdate',
      ),
      new TableMapping(
        'market_insight_job_title',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'market_insight_job_title',
        '',
      ),
      new TableMapping(
        'market_insight_job_title_vote',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'market_insight_job_title_vote',
        '',
      ),
      new TableMapping(
        'market_value_instruction_feedback',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'market_value_instruction_feedback',
        '',
      ),
      new TableMapping(
        'marketing_banner_tracking',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'marketing_banner_tracking',
        '',
      ),
      new TableMapping(
        'match_job_history',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'match_job_history',
        '',
      ),
      new TableMapping(
        'member_role',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'member_role',
        'updated',
      ),
      new TableMapping(
        'member_role_users',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'member_role_users',
        '',
      ),
      new TableMapping(
        'message_processed',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'message_processed',
        'updatedAt',
      ),
      new TableMapping(
        'mock_function',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'mock_function',
        '',
      ),
      new TableMapping(
        'noti_message',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'noti_message',
        'updated',
      ),
      new TableMapping(
        'notification',
        'notification_id',
        process.env.MONGODB_DATABASE_OTHER,
        'notification',
        'lastUpdate',
      ),
      new TableMapping(
        'notification_channel_setting',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'notification_channel_setting',
        '',
      ),
      new TableMapping(
        'payment',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'payment',
        'updatedAt',
      ),
      new TableMapping(
        'payment_orgtrial',
        'org_id',
        process.env.MONGODB_DATABASE_OTHER,
        'payment_orgtrial',
        '',
      ),
      new TableMapping(
        'potiential_candidate_feedback',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'potiential_candidate_feedback',
        'updated',
      ),
      new TableMapping(
        'promotion',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'promotion',
        'lastUpdate',
      ),
      new TableMapping(
        'push_notifications_apnsdevice',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'push_notifications_apnsdevice',
        '',
      ),
      new TableMapping(
        'push_notifications_gcmdevice',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'push_notifications_gcmdevice',
        '',
      ),
      new TableMapping(
        'push_notifications_webpushdevice',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'push_notifications_webpushdevice',
        '',
      ),
      new TableMapping(
        'push_notifications_wnsdevice',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'push_notifications_wnsdevice',
        '',
      ),
      new TableMapping(
        'question',
        'question_id',
        process.env.MONGODB_DATABASE_OTHER,
        'question',
        'updated_date',
      ),
      new TableMapping(
        'question_category',
        'category_id',
        process.env.MONGODB_DATABASE_OTHER,
        'question_category',
        'updated_date',
      ),
      new TableMapping(
        'r_banner',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'r_banner',
        'updatedAt',
      ),
      new TableMapping(
        'r_banner_action',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'r_banner_action',
        'updatedAt',
      ),
      new TableMapping(
        'reason_unsubscribed',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'reason_unsubscribed',
        '',
      ),
      new TableMapping(
        'recruiter',
        'recruiter_id',
        process.env.MONGODB_DATABASE_OTHER,
        'recruiter',
        'lastUpdate',
      ),
      new TableMapping(
        'recruiter_activity',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'recruiter_activity',
        '',
      ),
      new TableMapping(
        'recruiter_candidatestatus',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'recruiter_candidatestatus',
        'updated',
      ),
      new TableMapping(
        'recruiter_candidatestatusmessage',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'recruiter_candidatestatusmessage',
        '',
      ),
      new TableMapping(
        'recruiter_contact',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'recruiter_contact',
        'update_at',
      ),
      new TableMapping(
        'recruiter_first_activity_date',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'recruiter_first_activity_date',
        '',
      ),
      new TableMapping(
        'recruiter_jobjmcredit',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'recruiter_jobjmcredit',
        'updated',
      ),
      new TableMapping(
        'recruiter_jobjmcreditlog',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'recruiter_jobjmcreditlog',
        'updated',
      ),
      new TableMapping(
        'recruiter_jobjmcreditplan',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'recruiter_jobjmcreditplan',
        '',
      ),
      new TableMapping(
        'recruiter_last_activity_date',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'recruiter_last_activity_date',
        '',
      ),
      new TableMapping(
        'recruiter_payment',
        'recruiter_payment_id',
        process.env.MONGODB_DATABASE_OTHER,
        'recruiter_payment',
        '',
      ),
      new TableMapping(
        'referral_link',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'referral_link',
        'updated',
      ),
      new TableMapping(
        'relationship',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'relationship',
        'updatedAt',
      ),
      new TableMapping(
        'roles',
        'role_id',
        process.env.MONGODB_DATABASE_OTHER,
        'roles',
        'lastUpdate',
      ),
      new TableMapping(
        'rss_category_management',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'rss_category_management',
        'updatedAt',
      ),
      new TableMapping(
        'rss_feed_management',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'rss_feed_management',
        'updatedAt',
      ),
      new TableMapping(
        'salary',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'salary',
        'updatedAt',
      ),
      new TableMapping(
        'salary_review',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'salary_review',
        'updatedAt',
      ),
      new TableMapping(
        'salary_review_additional_income',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'salary_review_additional_income',
        'updatedAt',
      ),
      new TableMapping(
        'schedule',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'schedule',
        '',
      ),
      new TableMapping(
        'segment',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'segment',
        'updatedAt',
      ),
      new TableMapping(
        'segment_filter_employment_type',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'segment_filter_employment_type',
        '',
      ),
      new TableMapping(
        'segment_filter_industry',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'segment_filter_industry',
        '',
      ),
      new TableMapping(
        'segment_member',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'segment_member',
        'updatedAt',
      ),
      new TableMapping(
        'sort_type',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'sort_type',
        'updatedAt',
      ),
      new TableMapping(
        'suggested_cv',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'suggested_cv',
        'updatedAt',
      ),
      new TableMapping(
        'suggested_job_title',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'suggested_job_title',
        'updatedAt',
      ),
      new TableMapping(
        'suggested_job_title_click',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'suggested_job_title_click',
        '',
      ),
      new TableMapping(
        'suggested_skill',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'suggested_skill',
        'updatedAt',
      ),
      new TableMapping(
        'tag',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'tag',
        'updated',
      ),
      new TableMapping(
        'tag_candidate_job',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'tag_candidate_job',
        'updatedAt',
      ),
      new TableMapping(
        'tag_function',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'tag_function',
        'updatedAt',
      ),
      new TableMapping(
        'tag_jh',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'tag_jh',
        'updatedAt',
      ),
      new TableMapping(
        'tag_sub_function',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'tag_sub_function',
        'updatedAt',
      ),
      new TableMapping(
        'talent_view',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'talent_view',
        'updatedAt',
      ),
      new TableMapping(
        'talent_view_raw',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'talent_view_raw',
        '',
      ),
      new TableMapping(
        'tatent_keyword',
        'keyword_id',
        process.env.MONGODB_DATABASE_OTHER,
        'tatent_keyword',
        'updated',
      ),
      new TableMapping(
        'test_job',
        'job_id',
        process.env.MONGODB_DATABASE_OTHER,
        'test_job',
        'lastUpdate',
      ),
      new TableMapping(
        'tester_email',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'tester_email',
        'updatedAt',
      ),
      new TableMapping(
        'thumbdown_reason',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'thumbdown_reason',
        'updatedAt',
      ),
      new TableMapping(
        'token_update_interview',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'token_update_interview',
        'updatedAt',
      ),
      new TableMapping(
        'top_company',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'top_company',
        'updatedAt',
      ),
      new TableMapping(
        'tracking_event_admin',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'tracking_event_admin',
        'updatedAt',
      ),
      new TableMapping(
        'unlock_candidate_history',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'unlock_candidate_history',
        'updatedAt',
      ),
      new TableMapping(
        'unlock_candidate_request',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'unlock_candidate_request',
        'updated',
      ),
      new TableMapping(
        'unlock_request',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'unlock_request',
        'updated',
      ),
      new TableMapping(
        'unlocked_talent_history',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'unlocked_talent_history',
        'updated',
      ),
      new TableMapping(
        'year_of_experience',
        'id',
        process.env.MONGODB_DATABASE_OTHER,
        'year_of_experience',
        '',
      ),
    ];

    this.TABLE_MAPPINGS = [
      ...this.TABLE_MAPPING_ACTIVITY,
      ...this.TABLE_MAPPING_BLOG,
      ...this.TABLE_MAPPING_CHAT,
      ...this.TABLE_MAPPING_COMMON,
      ...this.TABLE_MAPPING_CANDIDATE,
      ...this.TABLE_MAPPING_CV,
      ...this.TABLE_MAPPING_JOB,
      ...this.TABLE_MAPPING_JOBSEEKER,
      ...this.TABLE_MAPPING_QUIZZ,
      ...this.TABLE_MAPPING_LUCKY_SPIN,
      ...this.TABLE_MAPPING_ORGANIZATION,
      ...this.TABLE_MAPPING_USERS,

      ...this.TABLE_MAPPING_OTHER,
    ];
  }

  getAllTableMapping() {
    return this.TABLE_MAPPINGS;
  }

  getAllMongoDatabase(): Set<string> {
    const mongoDatabases = new Set<string>();
    this.TABLE_MAPPINGS.forEach((tableMapping: TableMapping) => {
      mongoDatabases.add(tableMapping.mongoDatabase);
    });

    return mongoDatabases;
  }

  getAllTableMappingByDatabase(database: string): Array<TableMapping> {
    const tableMappings = [];

    for (const tableMapping of this.TABLE_MAPPINGS) {
      if (tableMapping.mongoDatabase == database)
        tableMappings.push(tableMapping);
    }

    return tableMappings;
  }

  getTableMappingForMysql(tableName: string): TableMapping {
    for (const tableMapping of this.TABLE_MAPPINGS) {
      if (tableMapping.mysqlTable == tableName) return tableMapping;
    }

    return null;
  }

  getTableMappingForMongodb(collection: string): TableMapping {
    for (const tableMapping of this.TABLE_MAPPINGS) {
      if (tableMapping.mongoCollection == collection) return tableMapping;
    }

    return null;
  }
}
