mailer:
  - conId: default
    service: mailgun
    host: smtp.mailgun.org
    port: 587
    secure: false
    auth:
      api_key: XXX
      domain: mydomain.com
    sender: admin@mydomain.com
    templateDir: /template
  - conId: sendgrid
    service: SendGrid
    auth:
      apiKey: XXX
  - conId: ses
    service: ses
    auth:
      accessKeyId: XXX
      secretAccessKey: YYY
      region: ZZZ
  - conId: mailchimp
    service: Mailchimp
    auth:
      user: XXX
      pass: YYY
