export enum HttpType {
  FORM = 'application/x-www-form-urlencoded',
  MULTIPART = 'multipart/form-data',
  JSON = 'application/json',
  XML = 'application/xml',
  PLAIN = 'text/plain',
  HTML = 'text/html',
  CSS = 'text/css',
  JS = 'text/javascript',
  IMAGE = 'image/*',
  JPEG = 'image/jpeg',
  PNG = 'image/png',
  GIF = 'image/gif',
  MP4 = 'video/mp4',
  JAVASCRIPT = 'application/javascript',
  PDF = 'application/pdf',
  ZIP = 'application/zip',
  SQL = 'application/sql',
  GRAPHQL = 'application/graphql',
  WORD = 'application/msword',
  EXCEL = 'application/vnd.ms-excel',
  POWERPOINT = 'application/vnd.ms-powerpoint',
}
