export enum ExceptionCode {
  // Common
  UNDEFINED = -1,
  SUCCESS = 0,
  SYSTEM_ERROR = 1,
  JWT_EXCEPTION = 2,
  INVALID_INPUT = 3,
  FORBIDDEN = 4,
  NOT_FOUND = 5,
  NOT_IMPLEMENTED = 6,
  // In the use case
  PHONE_REGISTERED = 7,
  PHONE_NOT_MATCH = 8,
  RESTRICT_SEND_OTP = 9,
  SMS_CODE_INVALID_OR_EXPIRED = 10,
  OTP_PENDING = 11,
  SESSION_INVALID = 12,
  TOKEN_NOT_MATCH = 13,
  SESSION_NOT_FOUND = 14,
  TOKEN_REVOKED = 15,
  TOKEN_OWNER_INVALID = 16,

  // Order
  DUPLICATE_ORDER = 20,
}
