/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "article": {
        "NOT_FOUND": string;
        "ALREADY_LIKED": string;
        "NOT_ALREADY_LIKED": string;
        "ALREADY_SHARED": string;
    };
    "auth": {
        "ACCESS_TOKEN_REQUIRED": string;
        "ACTIVE_CODE_REQUIRED": string;
        "AMAZON_IS_MAINTENANCE": string;
        "AMAZON_TOKEN_INVALID": string;
        "APPLE_IS_MAINTENANCE": string;
        "APPLE_TOKEN_INVALID": string;
        "AUTHORIZATION_HEADER_NOT_FOUND": string;
        "CONFIRMED_PASSWORD_NOT_MATCH": string;
        "CONFIRMED_PASSWORD_REQUIRED": string;
        "EMAIL_EXISTED": string;
        "EMAIL_NOT_MATCH": string;
        "EMAIL_REGISTERED": string;
        "FACEBOOK_IS_MAINTENANCE": string;
        "FACEBOOK_TOKEN_INVALID": string;
        "FIREBASE_IS_MAINTENANCE": string;
        "FIREBASE_TOKEN_INVALID": string;
        "GOOGLE_IS_MAINTENANCE": string;
        "GOOGLE_TOKEN_INVALID": string;
        "INVALID_ACCOUNT": string;
        "INVALID_PAYLOAD": string;
        "INVALID_TOKEN": string;
        "INVALID_TOKEN_FORMAT": string;
        "KAKAO_IS_MAINTENANCE": string;
        "KAKAO_TOKEN_INVALID": string;
        "NAVER_IS_MAINTENANCE": string;
        "NAVER_TOKEN_INVALID": string;
        "NICK_NAME_EXISTED": string;
        "OTP_PENDING": string;
        "PASSWORD_INVALID": string;
        "PASSWORD_REQUIRED": string;
        "PASSWORD_WEEK": string;
        "PROVIDER_CAN_NOT_PROCESS": string;
        "PROVIDER_NOT_ALLOWED": string;
        "PUBLIC_CODE_EXPIRED": string;
        "PUBLIC_CODE_INVALID": string;
        "REFRESH_TOKEN_NOT_SETUP": string;
        "REFRESH_TOKEN_REQUIRED": string;
        "RESTRICT_SEND_OTP": string;
        "SESSION_EXPIRED": string;
        "SESSION_INVALID": string;
        "SESSION_NOT_FOUND": string;
        "TOKEN_EXPIRED": string;
        "TOKEN_IDS_MUST_BE_ARRAY": string;
        "TOKEN_IDS_REQUIRED": string;
        "TOKEN_NOT_MATCH": string;
        "TOKEN_OWNER_INVALID": string;
        "TOKEN_REVOKED": string;
    };
    "common": {
        "ERROR_TITLE": string;
        "BAD_REQUEST": string;
        "UNAUTHORIZED": string;
        "FORBIDDEN": string;
        "NOT_FOUND": string;
        "NOT_ACCEPTABLE": string;
        "PROXY_AUTHENTICATION_REQUIRED": string;
        "REQUEST_TIMEOUT": string;
        "TOO_MANY_REQUESTS": string;
        "INTERNAL_SERVER_ERROR": string;
        "NOT_IMPLEMENTED": string;
        "SERVICE_UNAVAILABLE": string;
        "METHOD_NOT_ALLOWED": string;
        "INVALID_CONFIG": string;
        "INVALID_INPUT": string;
        "MICRO_METHOD_NOT_FOUND": string;
        "MICRO_SERVICE_NOT_FOUND": string;
        "INVALID_CLIENT_CONFIG": string;
        "CLIENT_CONNECTION_FAILED": string;
        "UNDERGOING_MAINTENANCE": string;
        "SOMETHING_WHEN_WRONG": string;
        "INVALID_FILE_TYPE": string;
        "INVALID_FILE_SIZE": string;
        "INVALID_FILE_COUNT": string;
    };
    "email": {
        "FOOTER": {
            "DISCLAIMER_1": string;
            "DISCLAIMER_2": string;
            "COMPANY_NAME": string;
            "DIRECTOR": string;
            "HOTLINE": string;
            "EMAIL": string;
            "TEL": string;
            "ADDRESS": string;
            "COMMUNITY": string;
            "POLICY": string;
            "TERM": string;
            "COPYRIGHT": string;
        };
        "VERIFY": {
            "SUBJECT": string;
            "TITLE": string;
            "CONTENT": {
                "HEADING": string;
                "GREETING": string;
                "LINE_1": string;
                "THANK": string;
                "SIGNATURE": string;
            };
        };
        "RESET": {
            "SUBJECT": string;
            "TITLE": string;
            "CONTENT": {
                "HEADING": string;
                "GREETING": string;
                "LINE_1": string;
                "LINE_2": string;
                "LINE_3": string;
                "LINE_4": string;
                "THANK": string;
                "SIGNATURE": string;
            };
        };
    };
    "user": {
        "USER_NOT_FOUND": string;
        "USER_NOT_ACTIVE": string;
        "USER_DISABLED": string;
        "EMAIL_EXISTED": string;
        "USERNAME_REQUIRED": string;
        "USERNAME_MIN_LENGTH": string;
        "USERNAME_MAX_LENGTH": string;
        "USER_NOT_SET_PASSWORD": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
