/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "auth": {
        "AUTHORIZATION_HEADER_NOT_FOUND": string;
        "INVALID_TOKEN": string;
        "REFRESH_TOKEN_NOT_SETUP": string;
        "INVALID_TOKEN_FORMAT": string;
        "TOKEN_EXPIRED": string;
        "INVALID_PAYLOAD": string;
        "INVALID_ACCOUNT": string;
    };
    "common": {
        "BAD_REQUEST": string;
        "UNAUTHORIZED": string;
        "FORBIDDEN": string;
        "NOT_FOUND": string;
        "NOT_ACCEPTABLE": string;
        "PROXY_AUTHENTICATION_REQUIRED": string;
        "REQUEST_TIMEOUT": string;
        "TOO_MANY_REQUESTS": string;
        "INTERNAL_SERVER_ERROR": string;
        "NOT_IMPLEMENTED": string;
        "SERVICE_UNAVAILABLE": string;
        "METHOD_NOT_ALLOWED": string;
        "INVALID_CONFIG": string;
        "INVALID_INPUT": string;
        "MICRO_METHOD_NOT_FOUND": string;
        "MICRO_SERVICE_NOT_FOUND": string;
        "INVALID_CLIENT_CONFIG": string;
        "CLIENT_CONNECTION_FAILED": string;
        "UNDERGOING_MAINTENANCE": string;
        "INVALID_FILE_TYPE": string;
        "INVALID_FILE_SIZE": string;
        "INVALID_FILE_COUNT": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
