/**
 * Quizz Constants
 */

export const QUIZZ_STATUS_PLAYING = 'PLAYING';
export const QUIZZ_STATUS_FINISHED = 'FINISHED';

export const ACTION_VIEW = 'VIEW';
export const ACTION_PLAY = 'PLAY';
export const ACTION_CHECKIN = 'CHECKIN';

export const SCORE_TYPE_QUIZZ = 'QUIZ';

export const RANKING_RANGE_WEEKY = 'WEEKLY';
export const RANKING_RANGE_ALL = 'ALL';

export const WEEKLY_DAYS = 7;

export const QUIZZ_STATUS_ACTIVE = 1;
export const QUIZZ_STATUS_INACTIVE = 0;

export const QUIZZ_ANSWER_CORRECT = 1;

export const QUIZZ_TYPE_TIMER = 'TIMER';

export const QUIZZ_MODE_PRIVATE = 'PRIVATE';
export const QUIZZ_MODE_PUBLISH = 'PUBLISH';

export const QUIZZ_RESULT_STATUS_PENDING = 'PENDING';

export const CLAIMED_YES = 1;
export const LAIMED_NO = 0;

export const READ_YES = 1;
export const READ_NO = 0;

export const VISIBLE_YES = 1;
export const VISIBLE_NO = 0;

export const IS_TIMEOUT_YES = 1;
export const IS_TIMEOUT_NO = 0;

export const TURN_ACTION_DAILY_CHECKIN = 1;
export const TURN_ACTION_APPLY_JOB = 2;
export const TURN_ACTION_ANSWER_WRONG_QUIZ_QUESTION = -1;
export const TURN_ACTION_USE_HINT_QUIZ_QUESTION = -1;
export const TURN_ACTION_PLAY_LUCKY_SPIN = -1;
export const TURN_ACTION_AWARD_TURN = 3;
export const TURN_ACTION_INTERVIEW_REVIEW = 2;
export const TURN_ACTION_SALARY_REVIEW = 2;
export const TURN_ACTION_UPDATE_PROFILE = 2;
export const TURN_ACTION_VIEW_COMPANY = 1;
export const TURN_ACTION_PLAY_TIMER_QUIZ = -1;
export const TURN_ACTION_REPLAY_TIMER_QUIZ = -1;
export const TURN_ACTION_AWARD_LUCKY_SPIN_TURN = 20;
export const ACTION_PLAY_TIMER_QUIZ_KEY = 'TURN_ACTION_PLAY_TIMER_QUIZ';
export enum GameTurnLogActions {
    TURN_ACTION_DAILY_CHECKIN = 'DAILY_CHECKIN',
    TURN_ACTION_APPLY_JOB = 'APPLY_JOB',
    TURN_ACTION_ANSWER_WRONG_QUIZ_QUESTION = 'ANSWER_WRONG_QUIZ_QUESTION',
    TURN_ACTION_USE_HINT_QUIZ_QUESTION = 'USE_HINT_QUIZ_QUESTION',
    TURN_ACTION_PLAY_LUCKY_SPIN = 'PLAY_LUCKY_SPIN',
    TURN_ACTION_AWARD_TURN = 'AWARD_TURN',
    TURN_ACTION_INTERVIEW_REVIEW = 'INTERVIEW_REVIEW',
    TURN_ACTION_SALARY_REVIEW = 'SALARY_REVIEW',
    TURN_ACTION_UPDATE_PROFILE = 'UPDATE_PROFILE',
    TURN_ACTION_VIEW_COMPANY = 'VIEW_COMPANY',
    TURN_ACTION_PLAY_TIMER_QUIZ = 'TURN_ACTION_PLAY_TIMER_QUIZ',
    TURN_ACTION_REPLAY_TIMER_QUIZ = 'TURN_ACTION_PLAY_AGAIN_TIMER_QUIZ',
    TURN_ACTION_AWARD_LUCKY_SPIN_TURN = 'AWARD_LUCKY_SPIN_TURN',
    TURN_ACTION_PLAY_LUCKY_SPIN_AWARD_TURN = 'PLAY_LUCKY_SPIN_AWARD_TURN'
}

export enum ActionsTurnValue {
    TURN_ACTION_DAILY_CHECKIN = 1,
    TURN_ACTION_APPLY_JOB = 2,
    TURN_ACTION_ANSWER_WRONG_QUIZ_QUESTION = -1,
    TURN_ACTION_USE_HINT_QUIZ_QUESTION = -1,
    TURN_ACTION_PLAY_LUCKY_SPIN = -1,
    TURN_ACTION_AWARD_TURN = 3,
    TURN_ACTION_INTERVIEW_REVIEW = 2,
    TURN_ACTION_SALARY_REVIEW = 2,
    TURN_ACTION_UPDATE_PROFILE = 2,
    TURN_ACTION_VIEW_COMPANY = 1,
    TURN_ACTION_PLAY_TIMER_QUIZ = -1,
    TURN_ACTION_REPLAY_TIMER_QUIZ = -1,
    TURN_ACTION_AWARD_LUCKY_SPIN_TURN = 20,
}

export enum LuckySpinItemTypes {
    ADDITIONAL_TURN = 'ADDITIONAL_TURN',
    QUOTE = 'QUOTE',
    GIFT = 'GIFT'
}